### ISSUE TITLE
avro/load.py regressed from version 1.6

### ISSUE THREAD

**Issue by quinarnold** [confluentinc/confluent-kafka-python#1141]
Description
===========
avro/load.py has regressed from version 1.6.0

https://github.com/confluentinc/confluent-kafka-python/blob/v1.6.0/src/confluent_kafka/avro/load.py
https://github.com/confluentinc/confluent-kafka-python/blob/v1.7.0/src/confluent_kafka/avro/load.py

Fails while loading schema:

Traceback (most recent call last):
  File "/home/qarnold/anaconda3/envs/airflow2.1/lib/python3.7/site-packages/airflow/executors/debug_executor.py", line 79, in _run_task
    ti._run_raw_task(job_id=ti.job_id, **params)  # pylint: disable=protected-access
  File "/home/qarnold/anaconda3/envs/airflow2.1/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/qarnold/anaconda3/envs/airflow2.1/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/qarnold/anaconda3/envs/airflow2.1/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/qarnold/anaconda3/envs/airflow2.1/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1336, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/qarnold/anaconda3/envs/airflow2.1/lib/python3.7/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/qarnold/anaconda3/envs/airflow2.1/lib/python3.7/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/c/users/qarnold/source/metadata-etl-airflow/CLDP-296/airflow/eg-wo/datahub/dags/teradata_datahub_etl.py", line 111, in produce_td_metadata
    record_schema = avro.load(AVROLOADPATH)
  File "/home/qarnold/anaconda3/envs/airflow2.1/lib/python3.7/site-packages/confluent_kafka/avro/load.py", line 33, in load
    return loads(f.read())
  File "/home/qarnold/anaconda3/envs/airflow2.1/lib/python3.7/site-packages/confluent_kafka/avro/load.py", line 25, in loads
    return schema.parse(schema_str)
AttributeError: module 'avro.schema' has no attribute 'parse'

How to reproduce
================
from confluent_kafka import avro
schema=avro.load(<file path>)

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [] Critical issue

workaround - pip install confluent-kafka==1.6.0 --upgrade

**Comment by quinarnold** [comment]
confluent_kafka.versiont() = ('1.7.0', 17235968)
confluent_kafka.libversion() = ('1.7.0', 17236223)
Python=3.7
avro-python3==1.8.2 (required for other reasons)

Operating system: wsl2 ubuntu

This error is not in the broker at all - unable to load avsc.

Works fine with 1.6.0

**Comment by saskell** [comment]
As an experiment I changed loads() in load.py for version 1.7.0 to look something like this:
```
def loads(schema_str):
    """ Parse a schema given a schema string """
    try:
        return schema.parse(schema_str)
    except AttributeError as e:
        # Try schema.Parse()
        try:
            return schema.Parse(schema_str)
        except schema.SchemaParseException as e:
            raise ClientError("Schema parse failed: %s" % (str(e)))
    except schema.SchemaParseException as e:
        raise ClientError("Schema parse failed: %s" % (str(e)))
```

That seemed to work....but dropping back to 1.6.0 worked for me as well.
